baseURL: "https://georg3tom.github.io/"
title: "George Tom"
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# googleAnalytics: UA-123-45

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  # description: "George Tom"
  keywords: [Blog, Portfolio, George, Tom]
  author: Me
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: true

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "favicon.ico"

  label:
    text: "~/george"
    icon: ""
    iconHeight: 35

  # home-info mode
  homeInfoParams:
    Title: "\U0001F44B Hola!"
    Content: "I'm George Tom. I'm pursuing an integrated Masters programme in Computer Science and Engineering at [IIIT Hyderabad](https://www.iiit.ac.in/), with guidance from both [C.V. Jawahar](https://faculty.iiit.ac.in/~jawahar/) and [Dimosthenis Karatzas](http://158.109.8.34/people/dimos/). My current research involves using multimodal learning to improve driver assistance systems."

  socialIcons:
    - name: github
      url: "https://github.com/georg3tom"
    - name: email
      url: "mailto:george.tom@research.iiit.ac.in"
    - name: googlescholar
      url: "https://scholar.google.com/citations?user=9xckHR0AAAAJ&hl=en"
    - name: linkedin
      url: "https://www.linkedin.com/in/georg3tom/"
    - name: instagram
      url: "https://www.instagram.com/georg3tom/"
    # - name: rss
    #   url: "/index.xml"
    # - name: pgp
    #   url: "index.xml"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search
      weight: 30
    # - identifier: example
    #   name: example.org
    #   url: https://example.org
    #   weight: 40
# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: false
    style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

googleAnalytics: G-FQT7QT52RK
